export const style = {
  position: "absolute",
  top: "50%",
  left: "50%",
  transform: "translate(-50%, -50%)",
  width: 800,
  bgcolor: "background.paper",
  borderRadius: "4px",
  display: "flex",
  flexDirection: "column",
  alignItems: "stretch",
  gap: 3,
  boxShadow: 24,
  p: 4,
};
